# To start/stop the services, use docker-compose up/down
version: "3.2"

services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: imse-frontend
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    depends_on:
      - backend-prod
    networks:
      applicationnet:

  backend-prod:
    build:
      # set context for build command explicitly
      context: ./backend
    image: imse-backend
    networks:
      applicationnet:

networks:
  applicationnet:
