# To start/stop the services, use docker-compose up/down
version: "3.2"

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: imse-frontend
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    depends_on:
      - backend-prod
    networks:
      applicationnet:
  backend-prod:
    container_name: backend-prod
    build:
      # set context for build command explicitly
      context: ./backend
    image: imse-backend
    networks:
      applicationnet:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_DATABASE: 'reservation_management_system'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234567890'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    networks:
      applicationnet:
  mongo:
      container_name: mongo
      image: mongo
      ports:
      - '27017:27017'

networks:
  applicationnet:
